export const cities = [
  {
    name: "臺北市",
    value: "Taipei",
    municipality: true,
    area: "north",
  },
  {
    name: "新北市",
    value: "NewTaipei",
    municipality: true,
    area: "north",
  },
  {
    name: "桃園市",
    value: "Taoyuan",
    municipality: true,
    area: "north",
  },
  {
    name: "臺中市",
    value: "Taichung",
    municipality: true,
    area: "central",
  },
  {
    name: "臺南市",
    value: "Tainan",
    municipality: true,
    area: "south",
  },
  {
    name: "高雄市",
    value: "Kaohsiung",
    municipality: true,
    area: "south",
  },
  {
    name: "基隆市",
    value: "Keelung",
    municipality: false,
    area: "north",
  },
  {
    name: "新竹市",
    value: "Hsinchu",
    municipality: false,
    area: "north",
  },
  {
    name: "新竹縣",
    value: "HsinchuCounty",
    municipality: false,
    area: "north",
  },
  {
    name: "苗栗縣",
    value: "MiaoliCounty",
    municipality: false,
    area: "central",
  },
  {
    name: "彰化縣",
    value: "ChanghuaCounty",
    municipality: false,
    area: "central",
  },
  {
    name: "南投縣",
    value: "NantouCounty",
    municipality: false,
    area: "central",
  },
  {
    name: "雲林縣",
    value: "YunlinCounty",
    municipality: false,
    area: "central",
  },
  {
    name: "嘉義縣",
    value: "ChiayiCounty",
    municipality: false,
    area: "south",
  },
  {
    name: "嘉義市",
    value: "Chiayi",
    municipality: false,
    area: "south",
  },
  {
    name: "屏東縣",
    value: "PingtungCounty",
    municipality: false,
    area: "south",
  },
  {
    name: "宜蘭縣",
    value: "YilanCounty",
    municipality: false,
    area: "north",
  },
  {
    name: "花蓮縣",
    value: "HualienCounty",
    municipality: false,
    area: "east",
  },
  {
    name: "臺東縣",
    value: "TaitungCounty",
    municipality: false,
    area: "east",
  },
  {
    name: "金門縣",
    value: "KinmenCounty",
    municipality: false,
    area: "island",
  },
  {
    name: "澎湖縣",
    value: "PenghuCounty",
    municipality: false,
    area: "island",
  },
  {
    name: "連江縣",
    value: "LienchiangCounty",
    municipality: false,
    area: "island",
  },
];
